### ISSUE TITLE
Calling a "find" on a search object more than once breaks the entire client 

### ISSUE THREAD

**Issue by justinfx** [voidshard/pywysteria#2]
If you create a search instance and call a find method on it more than once, the subsequent call fails while expected a response from the rpc. From that point on, the client seems to be unusable:

```
client = wysteria.Client()
client.connect()

search = client.Search()
search.params(item_type="collections", name="tiles")
search.find_collections()
# [<Collection 123123123>]
search.find_collections()
# ... wysteria/libs/nats/connector.py", line 101, in _waiting_data
# ... wysteria/libs/nats/client.py", line 315, in process_data
# ... wysteria/libs/nats/protocol.py", line 62, in matched
# return re.findall(reg, msg)[0]
# IndexError: list index out of range

search = client.Search()
search.params(item_type="collections", name="tiles")
search.find_collections()
# NatsClientException
```

The expected behavior would be that a search object could continuously be reused as opposed to being exhausted (and also disconnecting the client).

One other thing I noticed in this error is that the `NatsException.__init__()` implementation isn't calling the super __init__() and thus you aren't getting your actual message printed as part of raising the exception. It should probably either call the superclass init with the error message args, or populate the `self.args`

**Comment by voidshard** [comment]
Should be fixed now.
